
name: 'Upload file to Ali oss'
description: 'Upload assets to aliyun OSS'
branding:
  icon: 'upload-cloud'
  color: 'yellow'
inputs:
  region:
    required: true
  access-key-id:
    required: true
  access-key-secret:
    required: true
  bucket:
    required: true
  source:
    required: true
  target:
    required: false
outputs:
  url:
    description: oss url
runs:
  using: 'node12'
  main: 'src/index.js'
